name: thaparexpress
description: A new Flutter project.

publish_to:


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  cloud_firestore_web: ^2.3.0
  firebase_auth: ^3.0.1
  firebase_storage: ^10.0.1
  firebase_core: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/logo.jpg

